INSERT INTO teams (name) VALUES ('Boltaliðið');
INSERT INTO teams (name) VALUES ('Dripplararnir');
INSERT INTO teams (name) VALUES ('Skotföstu kempurnar');
INSERT INTO teams (name) VALUES ('Markaskorarnir');
INSERT INTO teams (name) VALUES ('Sigurliðið');
INSERT INTO teams (name) VALUES ('Risaeðlurnar');
INSERT INTO teams (name) VALUES ('Framherjarnir');
INSERT INTO teams (name) VALUES ('Fljótu fæturnir');
INSERT INTO teams (name) VALUES ('Vinningshópurinn');
INSERT INTO teams (name) VALUES ('Ósigrandi skotfólkið');
INSERT INTO teams (name) VALUES ('Óhemjurnar');
INSERT INTO teams (name) VALUES ('Hraðaliðið');