INSERT INTO teams (name, slug) VALUES ('Boltaliðið', 'boltalidid');
INSERT INTO teams (name, slug) VALUES ('Dripplararnir', 'dripplararnir');
INSERT INTO teams (name, slug) VALUES ('Skotföstu kempurnar', 'skotfostu-kempurnar');
INSERT INTO teams (name, slug) VALUES ('Markaskorarnir', 'markaskorarnir');
INSERT INTO teams (name, slug) VALUES ('Sigurliðið', 'sigurlidid');
INSERT INTO teams (name, slug) VALUES ('Risaeðlurnar', 'risaedlurnar');
INSERT INTO teams (name, slug) VALUES ('Framherjarnir', 'framherjarnir');
INSERT INTO teams (name, slug) VALUES ('Fljótu fæturnir', 'fljotu-faeturnir');
INSERT INTO teams (name, slug) VALUES ('Vinningshópurinn', 'vinningshopurinn');
INSERT INTO teams (name, slug) VALUES ('Ósigrandi skotfólkið', 'osigrandi-skotfolkid');
INSERT INTO teams (name, slug) VALUES ('Óhemjurnar', 'ohemjurnar');
INSERT INTO teams (name, slug) VALUES ('Hraðaliðið', 'hradalidid');